fix(unicode-regex): move the unicode non-alpha-num to separate pre-compiled regex
merged into #2451

there's an issue in deep dependencies of babel calls `regexpu`
to transpile unicode regex to ES5, but it has a bug causing

    TypeError: symbol.charCodeAt is not a function

https://github.com/mathiasbynens/regexpu-core/issues/13 unicodePropertyEscape: error when enclosed in square brackets #13

Luckily, it only transpiles regex literals,
https://github.com/mathiasbynens/regexpu#known-limitations
1. regexpu only transpiles regular expression literals, so things like RegExp('…', 'u') are not affected.

So here we can switch to pre-compiled regex with new constructor to avoid this issue; (and some performance gain)